version: '2'
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 54320:5432
    environment:
      - POSTGRES_DB=rankbot_db
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: always
  nginx:
    container_name: nginx
    build:
      dockerfile: nginx.dockerfile
      context: .
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
  app:
#    image: 'rankbot:rankbot'
    build:
      dockerfile: rankbot.dockerfile
      context: .
    container_name: app
    expose:
      - "8080"
    depends_on:
      - db
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rankbot_db
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USERNAME}
      - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_PASSWORD}
      - SPRING_SECURITY_USER_ROLES=ENDPOINT_ADMIN