version: '3.8'
services:
  db:
    image: postgres:14-bullseye
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    build:
      dockerfile: nginx.dockerfile
      context: .
    restart: always
    ports:
      - "80:80"
    #      - "443:443"
    depends_on:
      - app

  app:
    build:
      dockerfile: rankbot.dockerfile
      context: .
    container_name: app
    expose:
      - "8080"
    depends_on:
      - db
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}

volumes:
  db:
    driver: local