bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: .*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      hide-http-response-headers: true
      rate-limits:
        - expression: "getRemoteAddr()"
          bandwidths:
            - capacity: 30
              time: 30
              unit: seconds
              fixed-refill-interval: 30
              fixed-refill-interval-unit: seconds