spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ahian
    password: r04jb-m2khw-8g2u0-yizwv-6ahov
#    jdbc-url: jdbc:postgresql://db:5432/postgres
    jdbc-url: jdbc:postgresql://192.168.181.1:5432/postgres

rankbot:
  elo:
    scheduling: 600000

server:
  forward-headers-strategy: native
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"
