#!/usr/bin/env groovy

def tagImagen = "registry:5000/rankbot:0.9.0"
def ipServidor = "prod@10.69.203.240"
pipeline {

    agent any
    stages {

        stage('Build aplicación') {
            steps {
                script {
                    sh "docker build --target build -t ${tagImagen} ./rankbot-app"
                }
            }
        }
        stage('Generar imagen') {
            steps {
                script {
                    sh "docker build --target final -t ${tagImagen} ./rankbot-app"
                }
            }
        }
        stage('Save Docker Image as Tarball') {
            steps {
                // Save the Docker image as a tarball
                sh "docker save -o rankbot:0.9.0.tar.gz ${tagImagen}"
            }
        }
        stage('Copy Docker Image to Remote Server') {
            steps {
                // Start an SSH agent and add the private key associated with your SSH credentials
                sshagent(credentials: ['d8480059-bf09-46e4-9689-86542ca8eca7']) {
                    // Use scp to copy the local Docker image tarball to the remote server
                    sh "scp ${tagImagen}.tar.gz ubuntu@141.148.185.27:/home/ubuntu"
                }
            }
        }
//
//        stage('Desplegar a prod') {
//            steps {
//                script {
//                    sshagent(credentials : ['0f60cd81-f21f-448b-baa3-fbe738f0050b']) {
//
//                        sh "ssh -o StrictHostKeyChecking=no ${ipServidor} 'docker stop genesis || true'"
//                        sh "ssh -o StrictHostKeyChecking=no ${ipServidor} 'docker rm genesis || true'"
//                        sh "ssh -o StrictHostKeyChecking=no ${ipServidor} 'docker pull ${tagImagen}'"
//                        sh "ssh -o StrictHostKeyChecking=no ${ipServidor} 'docker run -d --name genesis --restart unless-stopped --network plataforma_default -v \"/etc/localtime:/etc/localtime:ro\" -v \"/etc/timezone:/etc/timezone:ro\" ${tagImagen}'"
//                    }
//                }
//            }
//        }
//
//        stage('Limpieza') {
//            steps{
//                sh "docker rmi ${tagImagen}"
//            }
//        }
    }
}