#!/usr/bin/env groovy

def tagImagen = "local/rankbot-auth:1.0.0"
def ipServidor = "ubuntu@141.148.185.27"
pipeline {

    agent any
    stages {

        stage('Git clone') {
            steps {
                script {
                    sshagent(credentials: ['0e7f6e3a-8c8e-49c7-ba2b-9fba8e4cfdcc']) {
                        sh "ssh -o StrictHostKeyChecking=no ${ipServidor} 'cd /tmp && rm -rf /tmp/rankbot && git clone --depth 1 git@github.com:ahianf/rankbot.git'"
                    }
                }
            }
        }

        stage('Build aplicación') {
            steps {
                script {
                    sshagent(credentials: ['0e7f6e3a-8c8e-49c7-ba2b-9fba8e4cfdcc']) {
                        sh "ssh -o StrictHostKeyChecking=no ${ipServidor} 'cd /tmp/rankbot/ && docker build --target build -t ${tagImagen} ./rankbot-auth'"
                    }
                }
            }
        }
        stage('Generar imagen') {
            steps {
                script {
                    sshagent(credentials: ['0e7f6e3a-8c8e-49c7-ba2b-9fba8e4cfdcc']) {
                        sh "ssh -o StrictHostKeyChecking=no ${ipServidor} 'cd /tmp/rankbot/ && docker build --target final -t ${tagImagen} ./rankbot-auth'"
                    }
                }
            }
        }

        stage('Desplegar a prod') {
            steps {
                script {
                    sshagent(credentials: ['0e7f6e3a-8c8e-49c7-ba2b-9fba8e4cfdcc']) {
                        sh "ssh -o StrictHostKeyChecking=no ${ipServidor} 'docker stop rankbot-auth || true'"
                        sh "ssh -o StrictHostKeyChecking=no ${ipServidor} 'docker rm rankbot-auth || true'"
                        sh "ssh -o StrictHostKeyChecking=no ${ipServidor} 'docker run -d --name rankbot-auth --restart unless-stopped --network rankbot_default -v \"/etc/localtime:/etc/localtime:ro\" -v \"/etc/timezone:/etc/timezone:ro\" ${tagImagen}'"
                    }
                }
            }
        }

        stage('Limpieza') {
            steps {
                script {
                    sshagent(credentials: ['0e7f6e3a-8c8e-49c7-ba2b-9fba8e4cfdcc']) {
                        sh "ssh -o StrictHostKeyChecking=no ${ipServidor} 'rm -rf /tmp/rankbot-auth'"
                    }
                }
            }
        }
    }
}